# Generated by Django 2.2 on 2019-11-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='date',
        ),
        migrations.AddField(
            model_name='location',
            name='jh',
            field=models.CharField(default='jour(s)', max_length=250),
        ),
        migrations.AddField(
            model_name='location',
            name='njh',
            field=models.IntegerField(default='1'),
        ),
    ]
